# Generated by Django 4.2.3 on 2023-07-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
